### ISSUE TITLE
 upload image error

### ISSUE THREAD

**Issue by chaiwenjun000** [byodian/oneimg#5]
<img width="967" alt="image" src="https://github.com/user-attachments/assets/d69a0b8d-f290-4d85-8acd-c2d93ff9e2d7">
rt

**Comment by chaiwenjun000** [comment]
I still have the same error.. after git pull this update

**Comment by chaiwenjun000** [comment]
and online demo: [oneimgai.com](https://oneimgai.com/) can't work too.

<img width="773" alt="image" src="https://github.com/user-attachments/assets/6ad1a45a-347a-485c-b5df-d247de9374e3">

**Comment by byodian** [comment]
Please provide your test steps including the uploaded file.
You can also provide a json file with the suffix `oneimg` which can be exported from the [oneimgai.com](https://oneimgai.com)
